[target.riscv32imc-unknown-none-elf]
# runner = "espflash flash --monitor"
# runner = "probe-rs run --chip esp32c3"
runner = "probe-rs run --chip esp32c3 --format idf"

[env]
ESP_LOGLEVEL="INFO"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",

  "-C", "link-arg=-Trom_functions.x",

  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  #
  # ADD following new flag ---
  "-C", "link-arg=-Tdefmt.x",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
